mcadmin/urls.py
from django.contrib import admin
from django.urls import path, include  # new

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('user.urls')),  # new
]

todo/urls.py
from django.urls import path
from .views import HomePageView

urlpatterns = [
    path("", HomePageView.as_view(), name="home"),
]

user/urls.py
from django.urls import include, path
from rest_framework import routers
from . import views, payment_views, player_views

router = routers.DefaultRouter()
router.register(r'payment', payment_views.PaymentViewSet)

urlpatterns = [
    path('', views.index, name='home'),
    path('login/', views.user_login, name='login'),
    path('signup/', views.user_signup, name='signup'),
    path('logout/', views.user_logout, name='logout'),
    path('player/', player_views.index, name='player'),
    path('payment/', payment_views.index, name='payment'),

    path('api/', include(router.urls)),
    # path("api/auth/", include('rest_framework.urls', namespace='rest_framework')),
]

todo/models.py
from django.db import models

class Todo(models.Model):
    todo = models.TextField()

    def __str__(self):
        return self.todo[:50]

user/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
import uuid
import logging
logger = logging.getLogger(__name__)
logging.basicConfig(filename='general.log', level=logging.INFO)

# Create your models here.
class Player(models.Model):
    id = models.ForeignKey(settings.AUTH_USER_MODEL,on_delete=models.CASCADE)
    uuid = models.UUIDField(primary_key=True, max_length=255)
    name = models.CharField(max_length=255)
    joined = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class AbstractPayment(models.Model):
    player = models.ForeignKey("Player", on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=5, decimal_places=2)
    date = models.DateTimeField(auto_now_add=True)

    class Meta:
        abstract = True

class Payment(AbstractPayment):
    def __str__(self):
        return self.player.name

user/forms.py
from django import forms 
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Player, Payment

class SignupForm(UserCreationForm):
    class Meta:
        model = User 
        fields = ['username', 'password1', 'password2']

    def __init__(self, *args, **kwargs):
        super(SignupForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs.update({'class': 'w-full'})
        self.fields['password1'].widget.attrs.update({'class': 'w-full'})
        self.fields['password2'].widget.attrs.update({'class': 'w-full'})

class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={"class": "w-full"}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={"class": "w-full"}))

todo/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Todo

class HomePageView(ListView):
    model = Todo
    template_name = "todo/home.html"

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout, get_user_model
from asgiref.sync import sync_to_async

from .forms import SignupForm, LoginForm
from .models import Player, Payment
from .minecraft import execute_command, color_codes_replacer

import asyncio

import logging
logger = logging.getLogger(__name__)
logging.basicConfig(filename='general.log', level=logging.INFO)

# Create your views here.
# Home page
async def index(request):
    whitelist_list = ""
    try: whitelist_list = await execute_command('whitelist', 'list')
    except Exception as e: logger.critical("err whitelist_list: %s" % e)

    status = ""
    try: status = await execute_command('tps') # get server tick and memory usage
    except Exception as e: logger.critical("err status: %s" % e)

    current_user = await sync_to_async(lambda: request.user)()
    payments = []
    current_player = None
    if await sync_to_async(lambda: request.user.is_staff)():
        try: payments = [p async for p in Payment.objects.all()]
        except Exception as e: logger.critical("err payments: %s" % e)
    else:
        # get the player from the user
        try: player = await sync_to_async(lambda: Player.objects.get(id=current_user))()
        except Exception as e: logger.critical("err player: %s" % e)

        try: payments = [p async for p in Payment.objects.filter(player=player)]
        except Exception as e: logger.critical("err payments: %s" % e)

    # convert players in payments to sync
    z__payments = []
    for payment in payments:
        payment.z__player = await sync_to_async(lambda: payment.player)()
        z__payments.append(payment)

    players = []
    try: players = [p async for p in Player.objects.all()]
    except Exception as e: logger.critical("err players: %s" % e)

    # convert players into sync
    z__players = []
    for player in players:
        player.z__user = await sync_to_async(lambda: player.id)()
        z__players.append(player)

    player = {}
    payment = {}
    if request.method == 'GET':
        p = request.GET.get("player", "")
        if p != "":
            try: player = await sync_to_async(lambda: Player.objects.get(uuid=p))()
            except Exception as e: logger.warning("err getting player from request: %s" % e)

        p = request.GET.get("payment", "")
        if p != "":
            try: payment = await sync_to_async(lambda: Payment.objects.get(id=p))()
            except Exception as e: logger.warning("err getting payment from request: %s" % e)

    if player:
        player.z__user = await sync_to_async(lambda: player.id)()

    if payment:
        payment.z__player = await sync_to_async(lambda: payment.player)()

    # get all users to be a player
    users = [u async for u in get_user_model().objects.all()]

    return render(request, 'index.html', {
        'whitelist_list': color_codes_replacer(whitelist_list),
        'status': color_codes_replacer(status),
        'z__players': z__players,
        'z__payments': z__payments,
        'users': users,
        "player": player,
        "payment": payment,
        "current_user": current_user,
        "is_staff": await sync_to_async(lambda: request.user.is_staff)(),
        "is_authenticated": await sync_to_async(lambda: request.user.is_authenticated)(),
    })

# signup page
def user_signup(request):
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('login')
    else:
        form = SignupForm()
    return render(request, 'signup.html', {'form': form})

# login page
def user_login(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            try: user = authenticate(request, username=username, password=password)
            except: user = None
            if user:
                login(request, user)
                return redirect('home')
    else:
        form = LoginForm()
    return render(request, 'login.html', {'form': form})

# logout page
def user_logout(request):
    logout(request)
    return redirect('login')

todo/templates/todo/home.html
{% load static %}
<h1>Django Todo App</h1>
<img src="{% static 'logo.svg' %}" alt="Fly logo"
    style="width:500px; height: 500px;">
<ul>
  {% for text in todo_list %}
    <li>{{ text.todo }}</li>
  {% endfor %}
</ul>

user/templates/_base.html
<!-- templates/_base.html -->

{% load compress %}
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="description" content="MC Admin">
    <meta name="keywords" content="Minecraft, Admin, Django">
    <meta name="author" content="https://gocs.me">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <link rel="icon" href="{% static 'logo.svg' %}" type="image/svg+xml">
    <title>MC Admin</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'src/output.css' %}">
    {% endcompress %}

</head>

<body class="bg-green-50">
    <div class="container mx-auto mt-4">
        {% block content %}
        {% endblock content %}
    </div>
    <script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js"></script>
</body>

</html>

user/templates/index.html
{% extends "_base.html" %}
{% block content %}
    {% if is_authenticated %}
        <ul class="flex justify-end font-mono text-xl font-black">
            <li class="flex-1"><a href="/"><p class="text-green-800">{{ request.user.username }}</p></a></li>
            <li><a href="{% url 'logout' %}" class="hover:bg-green-200">logout</a></li>
        </ul>

        {% if is_staff %}
            <p class="my-8">({{ status }})</p>
            <p class="my-8">{{ whitelist_list }}</p>
        {% else %}
            <p class="my-8"></p>
            <p class="my-8"></p>
        {% endif %}

        <div class="grid {% if is_staff %}grid-cols-5{% else %}grid-cols-1{% endif %} w-full">
            <div class="grid-span-5 {% if is_staff %}md:col-span-2{% endif %}">
                <h1 class="text-2xl font-black text-green-600">Payments</h1>
                {% if is_staff and not payment %}
                    <div class="w-full p-2">
                        <form action="/payment/" method="POST">
                            {% include 'save_payment.html' %}
                        </form>
                    </div>
                {% endif %}
                <div method="POST" class="relative overflow-x-auto p-2">
                    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" class="px-6 py-3">
                                    Player
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Amount
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Date
                                </th>
                                {% if is_staff %}
                                    <th scope="col" class="px-6 py-3">
                                        Actions
                                    </th>
                                {% endif %}
                            </tr>
                        </thead>
                        <tbody>
                            {% for p in z__payments %}
                                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                    {% if p.id == payment.id %}
                                        <td colspan="4">
                                            <div class="w-full p-2">
                                                <form action="/payment/" method="POST">
                                                    {% include 'save_payment.html' %}
                                                </form>
                                            </div>
                                        </td>
                                    {% else %}
                                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                            {{ p.z__player }}
                                        </th>
                                        <td class="px-6 py-4">
                                            {{ p.amount }}
                                        </td>
                                        <td class="px-6 py-4">
                                            {{ p.date }}
                                        </td>
                                        {% if is_staff %}
                                            <td class="px-6 py-4 flex gap-0.5">
                                                <a href="/?payment={{p.id}}" class="bg-yellow-400 hover:bg-yellow-600 text-white py-1 px-2">edit</a>
                                                <form action="/payment/" method="POST">
                                                    {% csrf_token %}
                                                    <button value="{{ p.id }}" name="delete"
                                                        class="bg-red-400 hover:bg-red-600 text-white py-1 px-2">delete</button>
                                                </form>
                                            </td>
                                        {% endif %}
                                    {% endif %}
                                </tr>
                            {% empty %}
                                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                    <td colspan="4" class="italic px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        No payments found
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% if is_staff %}
            <div class="grid-span-5 md:col-span-3">
                <h1 class="text-2xl font-black text-green-600">Players</h1>
                {% if not player %}
                    <div class="w-full p-2">
                        <form action="/player/" method="POST">
                            {% include 'save_player.html' %}
                        </form>
                    </div>
                {% endif %}
                <div class="relative overflow-x-auto p-2">
                    {% csrf_token %}
                    <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
                        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
                            <tr>
                                <th scope="col" class="px-6 py-3">
                                    Name
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    User
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    UUID
                                </th>
                                <th scope="col" class="px-6 py-3">
                                    Joined Date
                                </th>
                                <th scope="col" class="px-6 py-3">
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for p in z__players %}
                                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                    {% if player and player.uuid == p.uuid %}
                                        <td colspan="5">
                                            <div class="w-full p-2">
                                                <form action="/player/" method="POST">
                                                    {% include 'save_player.html' %}
                                                </form>
                                            </div>
                                        </td>
                                    {% else %}
                                        <th scope="row" class="px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                            {{ p.name }}
                                        </th>
                                        <td class="px-6 py-4">
                                            {{ p.z__user }}
                                        </td>
                                        <td class="px-6 py-4">
                                            {{ p.uuid }}
                                        </td>
                                        <td class="px-6 py-4">
                                            {{ p.joined }}
                                        </td>
                                        <td class="px-6 py-4 flex gap-0.5">
                                            <a href="/?player={{p.uuid}}" class="bg-yellow-400 hover:bg-yellow-600 text-white py-1 px-2">edit</a>
                                            <form action="/player/" method="POST">
                                                {% csrf_token %}
                                                <button value="{{ p.uuid }}" name="delete"
                                                    class="bg-red-400 hover:bg-red-600 text-white py-1 px-2">delete</button>
                                            </form>
                                        </td>
                                    {% endif %}
                                </tr>
                            {% empty %}
                                <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700">
                                    <td colspan="4" class="italic px-6 py-4 font-medium text-gray-900 whitespace-nowrap dark:text-white">
                                        No players found
                                    </td>
                                </tr>
                            {% endfor %}
                        </tbody>
                    </table>
                </div>
            </div>
            {% endif %}
        </div>
    {% else %}
        <ul class="flex justify-end font-mono text-xl font-black gap-3">
            <li class="flex-1"><h1>MC Admin</h1></li>
            <li><a href="{% url 'login' %}" class="p-2 border">Login</a></li>
            <li><a href="{% url 'signup' %}" class="p-2 border">Signup</a></li>
        </ul>
    {% endif %}

{% endblock content %}

user/templates/login.html
{% extends "_base.html" %}

{% block content %}
    <div class="flex justify-end w-full gap-3">
        <h1 class="p-3 text-xl font-mono font-bold">login</h1>
        <form method="POST" class="flex flex-col w-96 bg-green-200 p-3 gap-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="bg-green-600/30 p-3 uppercase">login</button>
            <a href="{% url 'signup' %}" class="bg-yellow-600/30 p-3">Dont have Account? Create!</a>
        </form>
    </div>
{% endblock content %}

user/templates/save_payment.html
{% csrf_token %}
<select name="player" class="mb-2" required value="{{ payment.z__player.uuid }}">
    {% for player in z__players %}
        <option value="{{ player.uuid }}" {% if payment.z__player.uuid == player.uuid %}selected{% endif %}>{{ player.name }}</option>
    {% endfor %}
</select>
<input type="number" name="amount" class="mb-2" placeholder="amount" required value="{{ payment.amount }}">
<button type="submit" class="h-full p-2 mb-2 bg-green-300 hover:bg-green-400" value="{{ payment.id }}" name="save">save</button>

user/templates/save_player.html
{% csrf_token %}
{% if request.GET.player %}
    <input type="text" readonly class="mb-2 bg-gray-200" placeholder="minecraft username" required value="{{ player.name }}">
{% else %}
    <input type="text" name="name" class="mb-2" placeholder="minecraft username" required value="{{ player.name }}">
{% endif %}
<select name="id" class="mb-2" required value="{{ player.z__user.id }}">
    {% for user in users %}
        <option value="{{ user.id }}" {% if player.z__user.id == user.id %}selected{% endif %}>{{ user.username }}</option>
    {% endfor %}
</select>
<button type="submit" class="h-full p-2 mb-2 bg-green-300 hover:bg-green-400" value="{{ player.uuid }}" name="save">save</button>

user/templates/signup.html
{% extends "_base.html" %}

{% block content %}
    <div class="flex justify-end w-full gap-3">
        <h1 class="p-3 text-xl font-mono font-bold">signup</h1>
        <form method="POST" class="flex flex-col w-96 bg-green-200 p-3 gap-3">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit" class="bg-green-600/30 p-3 uppercase">signup</button>
            <a href="{% url 'login' %}"  class="bg-yellow-600/30 p-3">Already have account?</a>
        </form>
    </div>
{% endblock content %}